let data = [ { id: 1, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/1_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/1_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/1_3.jpg' ], 
  name: 'Sweet Farmer\'s Vest', 
  rating: 4.5, 
  price: 16.99, 
  prime: false, 
  category_id: 1 }, 
{ id: 2, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/2_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/2_2.jpg' ], 
  name: 'Super Sweet Farmer\'s Suspenders', 
  rating: 2.5, 
  price: 7.99, 
  prime: true, 
  category_id: 1 }, 
{ id: 3, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/3_1.jpg' ], 
  name: 'Farmer\'s Stud Straw Skimmer Hat', 
  rating: 2.5, 
  price: 7.85, 
  prime: false, 
  category_id: 1 }, 
{ id: 4, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/4_1.jpg' ], 
  name: 'Super Fly Pilgrim Farmer Black Hat', 
  rating: 2.5, 
  price: 19.79, 
  prime: true, 
  category_id: 1 }, 
{ id: 5, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/5_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/5_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/5_3.jpg' ], 
  name: 'Sultry Bib Apron', 
  rating: 1.5, 
  price: 29.95, 
  prime: true, 
  category_id: 1 }, 
{ id: 6, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/6_1.jpeg' ], 
  name: 'They See Me Rollin They Hatin T-shirt', 
  rating: 3.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 7, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/7_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/7_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/7_3.jpg' ], 
  name: 'Straight Stylin Straight Clip Suspender', 
  rating: 2, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 8, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/8_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/8_2.jpg' ], 
  name: 'Little Sun Hat', 
  rating: 3, 
  price: 29.95, 
  prime: true, 
  category_id: 1 }, 
{ id: 9, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/9_1.jpg' ], 
  name: 'Child\'s Dress', 
  rating: 3, 
  price: 29.95, 
  prime: true, 
  category_id: 1 }, 
{ id: 10, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/10_1.jpg' ], 
  name: 'Forum Novelties Oversized Bonnet', 
  rating: 2.5, 
  price: 29.95, 
  prime: true, 
  category_id: 1 }, 
{ id: 11, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/11_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/11_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/11_3.jpg' ], 
  name: 'Felt Bonnet', 
  rating: 3, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 12, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/12_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/12_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/12_3.jpg' ], 
  name: 'Awesome Straw Hat', 
  rating: 3, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 13, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/13_2.jpg' ], 
  name: 'Awesome Plaid Shirt', 
  rating: 3.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 14, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/14_1.jpeg' ], 
  name: 'This Is My Farmers Costume Tee', 
  rating: 3, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 15, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/15_1.jpeg' ], 
  name: 'Farming Definition Shirt', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 16, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/16_1.jpg' ], 
  name: 'Farmer\'s Overalls', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 17, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/17_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/17_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/17_3.jpg' ], 
  name: 'Striped Suspenders', 
  rating: 3, 
  price: 29.95, 
  prime: true, 
  category_id: 1 }, 
{ id: 18, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/18_1.jpg' ], 
  name: 'Farm Dress 2.0', 
  rating: 3, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 19, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/19_1.jpg' ], 
  name: 'Farm Boy Clothes', 
  rating: 4, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 20, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/20_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/20_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/20_3.jpg' ], 
  name: 'Farm Dress 3.0', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 21, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/21_1.jpeg' ], 
  name: 'Formal Tee', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 22, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/22_1.jpg' ], 
  name: 'Underwraps Farm Dress', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 23, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/23_1.jpg' ], 
  name: 'The Plymouth Dress', 
  rating: 2.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 24, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/24_1.jpg' ], 
  name: 'Farm Girl Clothes', 
  rating: 3.5, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 25, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/25_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/25_2.jpg' ], 
  name: 'Farmer Women\'s Wear', 
  rating: 3, 
  price: 29.95, 
  prime: false, 
  category_id: 1 }, 
{ id: 26, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/26_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/26_2.jpg' ], 
  name: 'Wet Botton Shoofly Pie', 
  rating: 4, 
  price: 29.95, 
  prime: false, 
  category_id: 2 }, 
{ id: 27, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/27_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/27_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/27_3.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/27_4.jpg' ], 
  name: 'Homemade Whoopie Pie Variety Favorite', 
  rating: 3.5, 
  price: 31.95, 
  prime: false, 
  category_id: 2 }, 
{ id: 28, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/28_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/28_2.jpg' ], 
  name: 'Apple Butter', 
  rating: 3, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 29, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/29_1.jpg' ], 
  name: 'Fannie Farmer Cookbook', 
  rating: 3, 
  price: 43.23, 
  prime: true, 
  category_id: 2 }, 
{ id: 30, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/30_1.jpg' ], 
  name: 'Minerva Dairy Butter', 
  rating: 3.5, 
  price: 13.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 31, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/31_1.jpg',
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/31_3.jpg' ], 
  name: 'Country Popcorn', 
  rating: 2.5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 32, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/32_1.jpg' ], 
  name: 'Seedless Rasberry', 
  rating: 3, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 33, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/33_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/33_2.jpg' ],
  name: 'Bread n Butter Pickle', 
  rating: 3.5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 34, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/34_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/34_2.jpg' ], 
  name: 'Pickled Beets', 
  rating: 3, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 35, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/35_1.jpg' ], 
  name: 'Walnut Creek Hot Eggs', 
  rating: 4.5, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 36, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/36_1.jpg' ], 
  name: 'Wide Noodles', 
  rating: 1.5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 37, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/37_1.jpg' ], 
  name: 'Founding Farmers Cookbook', 
  rating: 3, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 38, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/38_1.jpg' ], 
  name: 'Country Popcorn Butter', 
  rating: 2.5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 39, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/39_1.jpg' ], 
  name: 'Pickled Hot Okra', 
  rating: 2, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 40, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/40_1.jpg' ], 
  name: 'Sweet Onion Relish Jars', 
  rating: 3, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 41, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/41_1.jpg' ], 
  name: 'Jalapeno Eggs', 
  rating: 2.5, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 42, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/42_1.jpg' ], 
  name: 'Parsley Noodles', 
  rating: 2, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 43, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/43_1.jpg' ], 
  name: 'Old Fashioned Sauerkraut', 
  rating: 4, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 44, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/44_1.jpg' ], 
  name: 'Farmers Market Premium Pet Food', 
  rating: 5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 45, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/45_1.jpg' ], 
  name: 'Green Cow Beef Tripe and Broth', 
  rating: 4, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 46, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/46_1.jpg' ], 
  name: 'Zesty Bread', 
  rating: 1.5, 
  price: 12.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 47, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/47_1.jpg' ], 
  name: 'Traffic Jam', 
  rating: 4.5, 
  price: 12.99, 
  prime: true, 
  category_id: 2 }, 
{ id: 48, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/48_1.jpg' ], 
  name: 'Country Salsa', 
  rating: 2.5, 
  price: 24.42, 
  prime: false, 
  category_id: 2 }, 
{ id: 49, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/49_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/49_2.jpg' ], 
  name: 'Pickled Asparagus', 
  rating: 4, 
  price: 8.99, 
  prime: false, 
  category_id: 2 }, 
{ id: 50, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/50_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/50_2.jpg' ], 
  name: 'Organic Sweet Potato', 
  rating: 2, 
  price: 2.43, 
  prime: true, 
  category_id: 2 }, 
{ id: 51, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/51_1.jpg' ], 
  name: 'The Farmer in All of Us: An American Portrait', 
  rating: 4, 
  price: 23.23, 
  prime: false, 
  category_id: 3 }, 
{ id: 52, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/52_1.jpg' ], 
  name: 'A Place to Call Home: Timeless Southern Charm', 
  rating: 2.5, 
  price: 7.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 53, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/53_1.jpg' ], 
  name: 'Silke Justice', 
  rating: 3, 
  price: 6.94, 
  prime: false, 
  category_id: 3 }, 
{ id: 54, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/54_1.jpg' ], 
  name: 'The Day The Farmers Quit', 
  rating: 2.5, 
  price: 3.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 55, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/55_1.jpg' ], 
  name: 'The Profitable Hobby Farm, How to Build a Sustainable Local Foods Business 1st Edition', 
  rating: 2, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 56, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/56_1.jpg' ], 
  name: 'Apple Farmer Annie', 
  rating: 4.5, 
  price: 11.23, 
  prime: false, 
  category_id: 3 }, 
{ id: 57, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/57_1.jpg' ], 
  name: 'The Farmers Wife', 
  rating: 2, 
  price: 2.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 58, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/58_1.jpg' ], 
  name: 'Farmer Boy', 
  rating: 2, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 59, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/59_1.jpg' ], 
  name: 'Who Took The Farmers Hat?', 
  rating: 3.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 60, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/60_1.jpg' ], 
  name: 'The Old Farmer\'s Almanac 2020', 
  rating: 3, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 61, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/61_1.jpg' ], 
  name: 'The Old Farmer\'s Almanac 2019', 
  rating: 4, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 62, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/62_1.jpg' ], 
  name: 'The Farmer\'s Bridge', 
  rating: 2.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 63, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/63_1.jpg' ], 
  name: 'The Animal\'s of Farmer Jones', 
  rating: 3.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 64, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/64_1.jpg' ], 
  name: 'The Complete Guide to Raising Pigs Everything You Need to Know', 
  rating: 3.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 65, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/65_1.jpg' ], 
  name: 'The Farm: A Novel', 
  rating: 3, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 66, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/66_1.jpg' ], 
  name: 'Start Your Farm: The Authoritative Guide to Becoming a Farmer', 
  rating: 1.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 67, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/67_1.jpg' ], 
  name: 'Ragweed\'s Farm Dog Handbook', 
  rating: 2, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 68, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/68_1.jpg' ], 
  name: 'Night Night Farm', 
  rating: 3, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 69, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/69_1.jpg' ], 
  name: 'Sleep Tight Farm', 
  rating: 3.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 70, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/70_1.jpg' ], 
  name: 'Peek-a-Boo Farm', 
  rating: 5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 71, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/71_1.jpg' ], 
  name: 'Mrs Wishy-Washy\'s Farm', 
  rating: 2.5, 
  price: 1.49, 
  prime: false, 
  category_id: 3 }, 
{ id: 72, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/72_1.jpg' ], 
  name: 'Farm Girl', 
  rating: 3.5, 
  price: 15.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 73, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/73_1.jpg' ], 
  name: 'Glad Farm: A Memoir', 
  rating: 4, 
  price: 3.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 74, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/74_1.jpg' ], 
  name: 'Saving Emma The Pig (The Biggest Little Farm)', 
  rating: 1.5, 
  price: 1.99, 
  prime: false, 
  category_id: 3 }, 
{ id: 75, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/75_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/75_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/75_3.jpg' ], 
  name: 'Harrisville Designs Lap Loom (Style A)', 
  rating: 3.5, 
  price: 78.34, 
  prime: true, 
  category_id: 3 }, 
{ id: 76, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/76_1.jpg' ], 
  name: 'Large Wooden Toy Semi Truck Set with 30 Building Blocks', 
  rating: 3.5, 
  price: 34.54, 
  prime: false, 
  category_id: 4 }, 
{ id: 77, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/77_1.jpg' ], 
  name: 'Wooden Toy Car Roller Coaster Run - Child-Safe Red/Yellow Finish', 
  rating: 3.5, 
  price: 2.45, 
  prime: false, 
  category_id: 4 }, 
{ id: 78, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/78_1.jpg' ], 
  name: 'Wooden Toy Horse & Buggy Penny Piggy Bank', 
  rating: 4, 
  price: 23.56, 
  prime: false, 
  category_id: 4 }, 
{ id: 79, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/79_1.jpg' ], 
  name: 'Deluxe Wooden Kid\'s Toy Box Chest, Pink and Gray (Large - 42" Wide)', 
  rating: 2.5, 
  price: 23.32, 
  prime: false, 
  category_id: 4 }, 
{ id: 80, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/80_1.jpg' ], 
  name: 'Aurora World Inc. Cloth Doll', 
  rating: 3, 
  price: 232.53, 
  prime: false, 
  category_id: 4 }, 
{ id: 81, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/81_1.jpg' ], 
  name: 'Buggy Toys Wooden Cars Toy Set CPSIA Kid Safe Finish', 
  rating: 1, 
  price: 65.44, 
  prime: false, 
  category_id: 4 }, 
{ id: 82, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/82_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/82_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/82_3.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/82_4.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/82_5.jpg' ], 
  name: 'DE Spider Prank Scare Box，Wooden Surprise Box，Handmade Fun Practical Surprise Joke Boxes, Gags & Practical Joke Toys Halloween', 
  rating: 3, 
  price: 10.99, 
  prime: true, 
  category_id: 4 }, 
{ id: 83, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/83_1.jpg' ], 
  name: 'Wooden 8" Toy Train Play Set, Painted', 
  rating: 0, 
  price: 16.99, 
  prime: true, 
  category_id: 4 }, 
{ id: 84, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/84_1.jpg' ], 
  name: 'Motorcycle Toy Rocking Horse Wooden Solid Oak', 
  rating: 2.5, 
  price: 119.83, 
  prime: false, 
  category_id: 4 }, 
{ id: 85, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/85_1.jpg' ], 
  name: 'Wooden Heirloom Marble Roller Toy, Child-Safe (Harvest Stained Finish)', 
  rating: 2.5, 
  price: 119.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 86, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/86_1.jpg' ], 
  name: 'Forum Novelties Child Bonnet', 
  rating: 3.5, 
  price: 8.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 87, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/87_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/87_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/87_3.jpg' ], 
  name: 'Wooden Folding Corral Fence Toy', 
  rating: 3, 
  price: 21.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 88, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/88_1.jpg' ], 
  name: 'Wooden Marble Roller Machine Toy, Child-Safe Maple/Walnut Finish', 
  rating: 3, 
  price: 59.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 89, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/89_1.jpg' ], 
  name: 'Deluxe Wooden Pyramid Marble Track Roller Run Toy, Child-Safe Finish', 
  rating: 3, 
  price: 349.5, 
  prime: false, 
  category_id: 4 }, 
{ id: 90, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/90_1.jpg' ], 
  name: 'Buggy Toys Wooden Car Vertical Roller w/ Mini Wooden Cars, Walnut & Maple CPSIA Kid Safe Finish', 
  rating: 4, 
  price: 43.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 91, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/91_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/91_2.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/91_3.jpg' ], 
  name: 'Peaceful Classics Wooden Furniture 3-in-1 Childrens High Chair, Wooden Rocking Horse, Writing Desk Solid Oak Wood (Harvest)', 
  rating: 4, 
  price: 289, 
  prime: false, 
  category_id: 4 }, 
{ id: 92, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/92_1.jpg' ], 
  name: 'Lehman\'s Handcrafted Eli & Mattie Children\'s Rocking Chair', 
  rating: 4, 
  price: 104.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 93, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/93_1.jpg' ], 
  name: 'Buggy Toys Kid\'s Wooden Play Chairs, Harvest', 
  rating: 2, 
  price: 79.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 94, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/94_1.jpg' ], 
  name: 'Skeleteen Corn Pipe Costume Accessory - Fake Toy Prop Pipe Accessories - 1 Piece', 
  rating: 3, 
  price: 6.99, 
  prime: true, 
  category_id: 4 }, 
{ id: 95, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/95_1.jpg' ], 
  name: 'Jacobson Hat Company Child\'s Cocoa Straw Cowboy', 
  rating: 2.5, 
  price: 13.56, 
  prime: true, 
  category_id: 4 }, 
{ id: 96, 
  image:  
   [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/96_1.jpg', 
     'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/96_2.jpg' ], 
  name: 'Wooden Toy Dump Truck, Child-Safe Finish', 
  rating: 4, 
  price: 39.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 97, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/97_1.jpg' ], 
  name: 'Buggy Toys Kid\'s Wooden Play Sink / Stove CPSIA Kid Safe Finish, Harvest', 
  rating: 3, 
  price: 319.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 98, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/98_1.jpg' ], 
  name: 'Berlin Flyer Ride Sport Wagon for Kids, All Terrain - Made In the USA - Huge No-Flat Tires - No-Pinch Handle & No-Tip Steering, 300 lb Limit - F410-SS Wagon', 
  rating: 3, 
  price: 156.99, 
  prime: false, 
  category_id: 4 }, 
{ id: 99, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/99_1.jpg' ], 
  name: 'Buggy Toys Rebekah\'s Collection Doll Crib for 12" - 18" Dolls, CPSIA Kid Safe Finish', 
  rating: 3.5, 
  price: 78.59, 
  prime: false, 
  category_id: 4 }, 
{ id: 100, 
  image: [ 'https://amishon.s3.us-east-2.amazonaws.com/PicturesForFEC/100_1.jpg' ], 
  name: 'The Original Adult Tree Swing (Tangy Orange)', 
  rating: 2.5, 
  price: 59.99, 
  prime: false, 
  category_id: 4 } ] 

module.exports = { data }



// let newNames = ['Sweet Farmer\'s Vest', 'Super Sweet Farmer\'s Suspenders', "Farmer's Stud Straw Skimmer Hat", "Super Fly Pilgrim Farmer Black Hat", "Sultry Bib Apron", "They See Me Rollin They Hatin T-shirt", "Straight Stylin Straight Clip Suspender", "Little Sun Hat", "Child's Dress", "Forum Novelties Oversized Bonnet", "Felt Bonnet", "Awesome Straw Hat", "Awesome Plaid Shirt", "This Is My Farmers Costume Tee", "Farming Definition Shirt", "Farmer's Overalls", "Striped Suspenders", "Farm Dress 2.0", "Farm Boy Clothes", "Farm Dress 3.0", "Formal Tee", "Underwraps Farm Dress", "The Plymouth Dress", "Farm Girl Clothes", "Farmer Women's Wear", "Wet Botton Shoofly Pie", "Homemade Whoopie Pie Variety Favorite", "Apple Butter", "Fannie Farmer Cookbook", "Minerva Dairy Butter", "Country Popcorn", "Seedless Rasberry", "Bread n Butter Pickle", "Pickled Beets", "Walnut Creek Hot Eggs", "Wide Noodles", "Founding Farmers Cookbook", "Country Popcorn Butter", "Pickled Hot Okra", "Sweet Onion Relish Jars", "Jalapeno Eggs", "Parsley Noodles", "Old Fashioned Sauerkraut", "Farmers Market Premium Pet Food", "Green Cow Beef Tripe and Broth", "Zesty Bread", "Traffic Jam", "Meduim Amish Wedding Salsa", "Pickled Asparagus", "Organic Sweet Potato", "The Farmer in All of Us: An American Portrait", "A Place to Call Home: Timeless Southern Charm", "Silke Justice", "The Day The Farmers Quit", "The Profitable Hobby Farm, How to Build a Sustainable Local Foods Business 1st Edition", "Apple Farmer Annie", "The Farmers Wife", "Farmer Boy", "Who Took The Farmers Hat?", "The Old Farmer's Almanac 2020", "The Old Farmer's Almanac 2019", "The Farmer's Bridge", "The Animal's of Farmer Jones", "The Complete Guide to Raising Pigs Everything You Need to Know", "The Farm: A Novel", "Start Your Farm: The Authoritative Guide to Becoming a Farmer", "Ragweed's Farm Dog Handbook", "Night Night Farm", "Sleep Tight Farm", "Peek-a-Boo Farm", "Mrs Wishy-Washy's Farm", "Farm Girl", "Glad Farm: A Memoir", "Saving Emma The Pig (The Biggest Little Farm)", "Harrisville Designs Lap Loom (Style A)", "Large Wooden Toy Semi Truck Set with 30 Building Blocks", "Wooden Toy Car Roller Coaster Run - Child-Safe Red/Yellow Finish", "Wooden Toy Horse & Buggy Penny Piggy Bank", "Deluxe Wooden Kid's Toy Box Chest, Pink and Gray (Large - 42\" Wide)", "Aurora World Inc. Cloth Doll", "Buggy Toys Wooden Cars Toy Set CPSIA Kid Safe Finish", "DE Spider Prank Scare Box，Wooden Surprise Box，Handmade Fun Practical Surprise Joke Boxes, Gags & Practical Joke Toys Halloween", "Wooden 8\" Toy Train Play Set, Painted", "Motorcycle Toy Rocking Horse Wooden Solid Oak", "Wooden Heirloom Marble Roller Toy, Child-Safe (Harvest Stained Finish)", "Forum Novelties Child Bonnet", "Wooden Folding Corral Fence Toy", "Wooden Marble Roller Machine Toy, Child-Safe Maple/Walnut Finish", "Deluxe Wooden Pyramid Marble Track Roller Run Toy, Child-Safe Finish", "Buggy Toys Wooden Car Vertical Roller w/ Mini Wooden Cars, Walnut & Maple CPSIA Kid Safe Finish", "Peaceful Classics Wooden Furniture 3-in-1 Childrens High Chair, Wooden Rocking Horse, Writing Desk Solid Oak Wood (Harvest)", "Lehman's Handcrafted Eli & Mattie Children's Rocking Chair", "Buggy Toys Kid's Wooden Play Chairs, Harvest", "Skeleteen Corn Pipe Costume Accessory - Fake Toy Prop Pipe Accessories - 1 Piece", "Jacobson Hat Company Child's Cocoa Straw Cowboy", "Wooden Toy Dump Truck, Child-Safe Finish", "Buggy Toys Kid's Wooden Play Sink / Stove CPSIA Kid Safe Finish, Harvest", "Berlin Flyer Ride Sport Wagon for Kids, All Terrain - Made In the USA - Huge No-Flat Tires - No-Pinch Handle & No-Tip Steering, 300 lb Limit - F410-SS Wagon", "Buggy Toys Rebekah's Collection Doll Crib for 12\" - 18\" Dolls, CPSIA Kid Safe Finish", "The Original Adult Tree Swing (Tangy Orange)"]

// for (var i = 0; i < newNames.length; i++) {
//   data[i].name = newNames[i]
// }

// console.log(data)